config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'rooms#index'
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	require "opentok"
	def index
		@rooms = Room.order("created_at DESC")
		@new_room = Room.new()
	end

	def create
		@api_key = ENV['API_KEY']
    	opentok = OpenTok::OpenTok.new(ENV["API_KEY"], ENV["API_SECRET"])
    	session = opentok.create_session
    	@new_room = Room.new(room_params)
    	@new_room.session_id = session.session_id
    	respond_to do |format|
          if @new_room.save
      	    format.html { redirect_to '/rooms/#{@new_room.id}'}
          #redirect_to rooms_party_path
          else
            format.html { render :controller => 'rooms', :action => "index" }
          end
        end
	end

	def show
	    @api_key = ENV['API_KEY']
		opentok = OpenTok::OpenTok.new(ENV["API_KEY"], ENV["API_SECRET"])
		@room = Room.find(params[:id])
		@token = opentok.generate_token(@room.session_id)
	end
  
    private
    def room_params
      params.require(:room).permit(:id, :name, :session_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Opentokrubysamplepg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<div id="newRoom">
  <fieldset>
    <legend>Start a new party room</legend>
    <%= form_for(@new_room) do |f| %>
      Room Name: <%= f.text_field :name %><br/><br/>
      <%= f.submit %>
    <% end %>
  </fieldset>
</div>

<fieldset>
  <legend>Existing party rooms</legend>
  <table cellpadding="2" cellspacing="5">
    <tr>
      <th>Name</th>
      <th>Started</th>
    </tr>

    <% @rooms.each do |room| %>
      <tr>
        <td align="center" width="300px"><%= link_to room.name, room_path(room) %> </td>
        <td><%= room.created_at %></td>
      </tr>
    <% end %>
  </table>
</fieldset>

app/views/rooms/show.html.erb
    
    <script type="text/javascript">
        var apiKey = '<%= @api_key %>';
        var sessionId = '<%= @room.session_id %>';
        var token = '<%= @token %>';
    </script>
    <h2>Hello, World!</h2>

    <div id="videos">
      <div id="publisher"></div>
      <div id="subscribers"></div>
    </div>

<script>
// Handling all of our errors here by alerting them
function handleError(error) {
  if (error) {
    alert(error.message);
  }
}

initializeSession();

function initializeSession() {
  var session = OT.initSession(apiKey, sessionId);

  // Subscribe to a newly created stream
  session.on('streamCreated', function(event) {
    session.subscribe(event.stream, 'subscriber', {
      insertMode: 'append',
      width: '100%',
      height: '100%'
    }, handleError);
  });

  // Create a publisher
  var publisher = OT.initPublisher('publisher', {
    insertMode: 'append',
    width: '100%',
    height: '100%'
  }, handleError);

  // Connect to the session
  session.connect(token, function(error) {
    // If the connection is successful, publish to the session
    if (error) {
      handleError(error);
    } else {
      session.publish(publisher, handleError);
    }
  });
}
</script>